services:
  proxy:
    container_name: proxy-y4kccso-155039122172
    image: 'julianpoy/recipesage-selfhost-proxy:v4.0.0'
    ports:
      - '7270:80'
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-rggsk4k.entryPoints=http
      - 'traefik.http.routers.http-0-rggsk4k.rule=Host(`recipes.app.stri.nz`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-rggsk4k.service=http-0-rggsk4k
      - traefik.http.routers.https-0-rggsk4k.entryPoints=https
      - traefik.http.routers.https-0-rggsk4k.middlewares=gzip
      - 'traefik.http.routers.https-0-rggsk4k.rule=Host(`recipes.app.stri.nz`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-rggsk4k.service=https-0-rggsk4k
      - traefik.http.routers.https-0-rggsk4k.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-rggsk4k.tls=true
      - traefik.http.services.http-0-rggsk4k.loadbalancer.server.port=80
      - traefik.http.services.https-0-rggsk4k.loadbalancer.server.port=80
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 7270}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://recipes.app.stri.nz'
      - caddy_ingress_network=y4kccso
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=proxy-y4kccso-155039122172
      - coolify.pullRequestId=0
  static:
    container_name: static-y4kccso-155039124718
    image: 'julianpoy/recipesage-selfhost:static-v2.13.3'
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=static-y4kccso-155039124718
      - coolify.pullRequestId=0
  api:
    container_name: api-y4kccso-155039125038
    image: 'julianpoy/recipesage-selfhost:api-v2.13.3'
    depends_on:
      - postgres
      - typesense
      - pushpin
      - browserless
    command: 'sh -c "npx prisma migrate deploy; npx ts-node --swc --project packages/backend/tsconfig.json packages/backend/src/bin/www"'
    environment:
      - STORAGE_TYPE=filesystem
      - FILESYSTEM_STORAGE_PATH=/rs-media
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - 'DATABASE_URL=postgresql://recipesage_selfhost:recipesage_selfhost@postgres:5432/recipesage_selfhost'
      - GCM_KEYPAIR
      - SENTRY_DSN
      - 'GRIP_URL=http://pushpin:5561/'
      - GRIP_KEY=changeme
      - SEARCH_PROVIDER=typesense
      - 'TYPESENSE_NODES=[{"host": "typesense", "port": 8108, "protocol": "http"}]'
      - TYPESENSE_API_KEY=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - 'INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3000/'
    volumes:
      - 'apimedia:/rs-media'
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=api-y4kccso-155039125038
      - coolify.pullRequestId=0
  typesense:
    container_name: typesense-y4kccso-155039125406
    image: 'typesense/typesense:0.24.1'
    volumes:
      - 'typesensedata:/data'
    command: '--data-dir /data --api-key=recipesage_selfhost --enable-cors'
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=typesense-y4kccso-155039125406
      - coolify.pullRequestId=0
  pushpin:
    container_name: pushpin-y4kccso-155039126532
    image: 'julianpoy/pushpin:2023-09-17'
    entrypoint: '/bin/sh -c'
    command:
      - 'sed -i "s/sig_key=changeme/sig_key=$$GRIP_KEY/" /etc/pushpin/pushpin.conf && echo "* $${TARGET},over_http" > /etc/pushpin/routes && pushpin --merge-output'
    environment:
      - GRIP_KEY=changeme
      - 'TARGET=api:3000'
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=pushpin-y4kccso-155039126532
      - coolify.pullRequestId=0
  postgres:
    container_name: postgres-y4kccso-155039127769
    image: 'postgres:16'
    environment:
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
    volumes:
      - 'postgresdata:/var/lib/postgresql/data'
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=postgres-y4kccso-155039127769
      - coolify.pullRequestId=0
  browserless:
    container_name: browserless-y4kccso-155039129244
    image: 'browserless/chrome:1.61.0-puppeteer-21.4.1'
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped
    networks:
      y4kccso: null
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.293
      - coolify.applicationId=3
      - coolify.type=application
      - coolify.name=browserless-y4kccso-155039129244
      - coolify.pullRequestId=0
volumes:
  apimedia:
    name: apimedia
  typesensedata:
    name: typesensedata
  postgresdata:
    name: postgresdata
networks:
  y4kccso:
    name: y4kccso
    external: true
